'use client'

import { useRef, useCallback } from 'react'
import type { TemplateSummary } from '@/app/api/share/template/[templateId]/route'

interface TemplateShareCardProps {
  summary: TemplateSummary
}

export default function TemplateShareCard({ summary }: TemplateShareCardProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)

  const generateImage = useCallback(() => {
    const canvas = canvasRef.current
    if (!canvas) return null

    const w = 600
    const lineCount = summary.days.reduce((sum, d) => sum + Math.min(d.exercises.length, 5) + 2, 0)
    const h = Math.max(500, 220 + lineCount * 20 + summary.days.length * 20)
    const dpr = 2
    canvas.width = w * dpr
    canvas.height = h * dpr
    canvas.style.width = `${w}px`
    canvas.style.height = `${h}px`

    const ctx = canvas.getContext('2d')
    if (!ctx) return null

    ctx.scale(dpr, dpr)

    // Background
    const grad = ctx.createLinearGradient(0, 0, w, h)
    grad.addColorStop(0, '#0a0a0c')
    grad.addColorStop(1, '#111115')
    ctx.fillStyle = grad
    ctx.fillRect(0, 0, w, h)

    // Accent strip
    const accentGrad = ctx.createLinearGradient(0, 0, w, 0)
    accentGrad.addColorStop(0, '#2563eb')
    accentGrad.addColorStop(1, '#3b82f6')
    ctx.fillStyle = accentGrad
    ctx.fillRect(0, 0, w, 4)

    // Branding
    ctx.fillStyle = '#888888'
    ctx.font = '500 12px system-ui, sans-serif'
    ctx.fillText('WORKOUT PLANNER', 30, 36)

    // Creator
    ctx.fillStyle = '#3b82f6'
    ctx.font = '600 16px system-ui, sans-serif'
    ctx.fillText(`@${summary.creator_username}`, 30, 66)

    // Template name
    ctx.fillStyle = '#f5f5f5'
    ctx.font = 'bold 28px system-ui, sans-serif'
    ctx.fillText(summary.name, 30, 104)

    // Plan type
    ctx.fillStyle = '#888888'
    ctx.font = '400 14px system-ui, sans-serif'
    ctx.fillText(summary.plan_type.replace(/_/g, ' ').toUpperCase(), 30, 128)

    // Stats
    const statY = 158
    ctx.fillStyle = 'rgba(255,255,255,0.04)'
    ctx.beginPath()
    ctx.roundRect(20, statY - 10, w - 40, 55, 8)
    ctx.fill()

    ctx.fillStyle = '#f5f5f5'
    ctx.font = 'bold 20px system-ui, sans-serif'
    ctx.fillText(String(summary.days.length), 30, statY + 18)
    ctx.fillStyle = '#666666'
    ctx.font = '400 11px system-ui, sans-serif'
    ctx.fillText('Days', 30, statY + 34)

    ctx.fillStyle = '#f5f5f5'
    ctx.font = 'bold 20px system-ui, sans-serif'
    ctx.fillText(String(summary.total_exercises), 200, statY + 18)
    ctx.fillStyle = '#666666'
    ctx.font = '400 11px system-ui, sans-serif'
    ctx.fillText('Exercises', 200, statY + 34)

    // Days
    let y = statY + 70

    for (const day of summary.days) {
      ctx.fillStyle = '#e5e5e5'
      ctx.font = '600 14px system-ui, sans-serif'
      ctx.fillText(day.day_label, 30, y)
      y += 22

      const maxEx = Math.min(day.exercises.length, 5)
      for (let i = 0; i < maxEx; i++) {
        ctx.fillStyle = '#3b82f6'
        ctx.font = '400 8px system-ui, sans-serif'
        ctx.fillText('●', 34, y)
        ctx.fillStyle = '#999999'
        ctx.font = '400 12px system-ui, sans-serif'
        ctx.fillText(day.exercises[i], 48, y)
        y += 18
      }
      if (day.exercises.length > 5) {
        ctx.fillStyle = '#666666'
        ctx.font = '400 11px system-ui, sans-serif'
        ctx.fillText(`+ ${day.exercises.length - 5} more`, 48, y)
        y += 18
      }
      y += 10
    }

    // Footer
    ctx.fillStyle = '#333333'
    ctx.fillRect(20, h - 50, w - 40, 1)
    ctx.fillStyle = '#555555'
    ctx.font = '400 11px system-ui, sans-serif'
    ctx.fillText('Generated by Workout Planner', 30, h - 22)

    return canvas
  }, [summary])

  const handleDownload = () => {
    const canvas = generateImage()
    if (!canvas) return

    const link = document.createElement('a')
    link.download = `template_${summary.name.replace(/\s/g, '_')}.png`
    link.href = canvas.toDataURL('image/png')
    link.click()
  }

  const handleShare = async () => {
    const canvas = generateImage()
    if (!canvas) return

    canvas.toBlob(async (blob) => {
      if (!blob) return
      const file = new File([blob], 'template.png', { type: 'image/png' })

      if (navigator.share && navigator.canShare?.({ files: [file] })) {
        try {
          await navigator.share({
            title: summary.name,
            text: `Check out this workout template: ${summary.name} — ${summary.days.length} days, ${summary.total_exercises} exercises`,
            files: [file],
          })
        } catch { /* cancelled */ }
      } else {
        handleDownload()
      }
    }, 'image/png')
  }

  return (
    <div className="space-y-3">
      <canvas ref={canvasRef} className="hidden" />
      <div className="flex gap-2">
        <button onClick={handleDownload} className="flex-1 py-2.5 px-4 rounded-lg border border-white/[0.08] text-foreground text-sm hover:bg-white/[0.04] transition-colors flex items-center justify-center gap-2">
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
          Download Card
        </button>
        <button onClick={handleShare} className="flex-1 py-2.5 px-4 btn-primary rounded-lg text-sm flex items-center justify-center gap-2">
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" /></svg>
          Share
        </button>
      </div>
    </div>
  )
}
